routes/web.php
<?php

use App\Http\Controllers\DocumentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['as' => 'document.', 'prefix' => 'document'], function () {
    Route::get('/', [DocumentController::class, 'index'])->name('index');
    Route::get('/search', [DocumentController::class, 'search'])->name('search');
    Route::get('/detail/{id}', [DocumentController::class, 'detail'])->name('detail');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public $table = 'categories_multi';
}

app/Models/Document.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    use HasFactory;

    public $table = "document";
}

app/Models/DocumentText.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DocumentText extends Model
{
    use HasFactory;

    public $table  = 'document_text_1';
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Document;
use App\Services\ElasticsearchService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class DocumentController extends Controller
{
    private const INDEX = "document,categories_multi";

    public function index()
    {
        return view('document');
    }

    public function detail($id)
    {
        $document = Document::where('doc_id', $id)->first();

        $docRelated = $this->docRelated($document->doc_name, 20, $document->doc_category_id);

        return view('detail', [
            'document' => $document,
            'data' => $docRelated['result'],
        ]);
    }

    public function search(Request $request)
    {
        $data = [];
        $count = 0;

        if (!is_null($request->keyword)) {
            $response = $this->searchByKeyword($request->keyword);

            $data = $response['result'];
            $count = $response['count'];
        }

        return view('document', [
            'data' => count($data) == 0 ? null : collect($data),
            'total' => $count,
        ]);
    }

    private function docRelated($text, $size, $categoryId)
    {
        $should = [];
        $es = new ElasticsearchService();

        $response = $es->getAnalyze(
            'index-customer-analyzer',
            ['analyzer' => 'document_vi_analyzer', 'text' => $text]
        );

        foreach ($response['tokens'] as $key) {
            Log::debug($key['token']);
            array_push(
                $should,
                ['match' => ['doc_name' => $key['token']]],
                ['match' => ['doc_name_no_accent' => $key['token']]]

            );
        }

        $query = [
            'size' => $size,
            '_source' => [
                "doc_id",
                'doc_path_extract',
                'doc_name',
                'doc_name_no_accent',
                'doc_tag'
            ],
            'query' => [
                "function_score" => [
                    'query' => [
                        'bool' => [
                            'should' => $should,
                            'must' => [
                                'match' => ['doc_category_id' => $categoryId]
                            ]
                        ],
                    ],
                    'script_score' => [
                        'script' => "_score + Math.log10(doc['doc_views'].value + 1)"
                    ],
                    'score_mode' => 'sum',
                    'boost_mode' => 'sum'
                ],
            ],
        ];

        return $this->mapResponse($this->searchELS(self::INDEX, $query));
    }

    private function searchByKeyword($keyword, $size = 20)
    {
        $query = [
            'indices_boost' => [
                ['categories_multi' => 3],
                ['document' => 1.5],
            ],
            'size' => $size,
            '_source' => [
                "doc_id",
                'doc_path_extract',
                'doc_name',
                'doc_name_no_accent',
                'doc_tag',
                'doc_category_id',
            ],
            'query' => [
                "function_score" => [
                    'query' => [
                        'bool' => [
                            'should' => [
                                [
                                    'match' => [
                                        'doc_name' => $keyword
                                    ]
                                ],
                                [
                                    'match' => [
                                        'doc_name_no_accent' => $keyword
                                    ]
                                ],
                                [
                                    'match' => [
                                        'cat_name' => $keyword
                                    ]
                                ],
                            ],
                        ],
                    ],
                    'script_score' => [
                        'script' => "_score + Math.log10(doc['doc_views'].value + 1)"
                    ],
                    'score_mode' => 'sum',
                    'boost_mode' => 'sum'
                ],
            ],
        ];

        return $this->mapResponse($this->searchELS(self::INDEX, $query));
    }

    private function searchELS($index, $query)
    {
        $es = new ElasticsearchService();
        return $es->search($index, $query);
    }

    private function mapResponse($response)
    {
        $result = isset($response['hits']['hits']) ? $response['hits']['hits'] : null;
        $count = isset($response['hits']['total']) ? $response['hits']['total']['value'] : null;

        return [
            'result' => $result,
            'count' => $count,
        ];
    }
}

resources/views/detail.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div style="padding: 10px;">
        <h2>Document detail</h2>
        <p> 
        <span style="font-weight : bold"> Id : </span> {{$document->doc_id}}</p>
        <p> 
        <span style="font-weight : bold"> Document name : </span> {{$document->doc_name}}</p>
        <p> 
        <span style="font-weight : bold"> Document name no access : </span> {{$document->doc_name_no_accent}}</p>
        <p> 
        <span style="font-weight : bold"> Document tag : </span> {{$document->doc_tag}}</p>
       
    </div>

     <div style="padding: 10px; margin: auto; margin-top: 30px; border-top: 1px solid black;">
        <h3 style="text-align: center;">
            Document related
        </h3>
        <div>
            @if(isset($data))

            @foreach ($data as $doc)

            <a href="{{route("document.detail", $doc['_source']['doc_id'])}}">
                <p> _score : {{ $doc['_score'] }} </p>
            </a>
            @foreach ($doc['_source'] as $key => $value)

            <span style="margin-left: 20px;"> {{ $key }} : {{ $value}} </span> <br/>

            @endforeach

            @endforeach

            @else
            <p>No results found</p>
            @endif
        </div>
    </div>

</body>

</html>

resources/views/document.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div style="text-align: center; width: 50%; margin: auto; border-radius: 10px; border: 1px solid black; padding: 10px;">
        <h2>Form search document</h2>
        <h4>Thêm độ ảnh hưởng của lượt view document lên kết quả tìm kiếm</h4>
        <p>
            score new = score cũ + number view
        </p>

        <form action="{{route('document.search')}}">
            <input type="text" value="{{ old('keyword') }}" name="keyword">
            <button type="submit">Search</button>
        </form>
    </div>

    <div style="padding: 10px; margin: auto; margin-top: 30px; border-top: 1px solid black;">
        <h3 style="text-align: center;">
            @if(isset($total) && $total > 0) {{$total}} @endif
            Result
        </h3>
        <div>
            @if(isset($data))

            @foreach ($data as $doc)

            <a href="{{route("document.detail", $doc['_source']['doc_id'])}}">
                <p> _score : {{ $doc['_score'] }} </p>
            </a>
            @foreach ($doc['_source'] as $key => $value)

            <span style="margin-left: 20px;"> {{ $key }} : {{ $value}} </span> <br/>

            @endforeach

            @endforeach

            @else
            <p>No results found</p>
            @endif
        </div>
    </div>

</body>

</html>